//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromptListItem
    {
        public int PromptListItemID { get; set; }
        public System.DateTime TriggerDate { get; set; }
        public int GardenID { get; set; }
        public int PromptListTypeID { get; set; }
        public string VegetableReference { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Complete { get; set; }
    
        public virtual Garden Garden { get; set; }
        public virtual PromptListType PromptListType { get; set; }
    }
}
