//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vegetable
    {
        public int VegetableID { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string VegetableImagePath { get; set; }
        public Nullable<int> WaterFrequency { get; set; }
        public string WaterInstructions { get; set; }
        public Nullable<int> HarvestDateMod { get; set; }
        public Nullable<int> SeedsPerSqFt { get; set; }
        public string ExtraSupportType { get; set; }
        public Nullable<int> YearlyHarvestAmount { get; set; }
        public Nullable<System.DateTime> SowDate { get; set; }
        public int GardenID { get; set; }
    
        public virtual Garden Garden { get; set; }
    }
}
